package de.htwg.chat;

import jakarta.persistence.*;

import java.util.Date;
import java.util.UUID;

/**
 * Represents the answer to the users input message.
 * The date is set to the current date and time when the answer is created.
 * the model should be set with the Modeltype Enum values.
 * The id is a UUID and will be autogenerated.
 * It uses the builder pattern to create a new answer.
 * It has a ManyToOne relationship with the Message class.
 *
 */
@Entity
public class Answer {

    @Id
    @GeneratedValue(generator = "UUID")
    private UUID id;

    @Column(length = 3000)
    private String answer;
    private String model;

    private Date date;

    @ManyToOne(targetEntity = Message.class)
    private Message message;

    public Answer() {
    }

    private Answer(AnswerBuilder answerBuilder){
        this.answer = answerBuilder.answer;
        this.date = answerBuilder.date;
        this.model = answerBuilder.model;
        this.message = answerBuilder.message;
    }

    public static class AnswerBuilder{
        private String answer;
        private Date date;
        private String model;
        private Message message;

        public AnswerBuilder() {
            this.date = new Date();
        }

        public AnswerBuilder answer(String answer){
            this.answer = answer;
            return this;
        }

        public AnswerBuilder date(Date date){
            this.date = date;
            return this;
        }

        public AnswerBuilder model(String model){
            this.model = model;
            return this;
        }

        public AnswerBuilder message(Message message){
            this.message = message;
            return this;
        }

        public Answer build(){
            return new Answer(this);
        }
    }
}
