
version: "3.8"

services:
  quarkus-service:
    image: "saschakiebler/thesis-chatbot"
    container_name: "thesis-chatbot"
    env_file:
      - .env
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://quarkus-db:5432/thesis-db
      - OPENAI_APIKEY=${OPENAI_APIKEY}
      - TOGETHERAI_API_KEY=${TOGETHERAI_API_KEY}
    volumes:
      - pdf_storage:/resources/pdfs
    ports:
      - "8080:8080"
    depends_on:
      - quarkus-db
    networks:
      - quarkus

  quarkus-db:
    image: "pgvector/pgvector:pg14"
    container_name: "quarkus-db"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=thesis-db
    volumes:
      - postgres_vector_volume:/var/lib/postgresql/data/
    ports:
      - "5431:5432"
    networks:
      - quarkus

networks:
  quarkus:


volumes:
  postgres_vector_volume:
  pdf_storage:
