package de.htwg.multipleChoice;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;

import java.util.UUID;

/**
 * Represents a lecture.
 * The id is a UUID and will be autogenerated.
 * It uses the builder pattern to create a new lecture.
 *
 */
@Entity
public class Lecture {

    @Id
    @GeneratedValue(generator = "UUID")
    private UUID id;
    private String name;
    private String description;

    public Lecture() {
    }

    public Lecture(String name, String description) {
        this.name = name;
        this.description = description;
    }

    public Lecture(String name, String description, UUID id) {
        this.name = name;
        this.description = description;
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public String getDescription() {
        return description;
    }

    public UUID getId() {
        return id;
    }

    public static LectureBuilder builder() {
        return new LectureBuilder();
    }

    public static class LectureBuilder {
        private String name;
        private String description;
        private UUID id;

        public LectureBuilder() {

        }

        public LectureBuilder name(String name) {
            this.name = name;
            return this;
        }

        public LectureBuilder description(String description) {
            this.description = description;
            return this;
        }

        public LectureBuilder id(UUID id) {
            this.id = id;
            return this;
        }

        public Lecture build() {
            return new Lecture(name, description, id);
        }
    }
}
