name: Docker

on:
  push:
    branches:
      - master

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log into registry ${{ env.REGISTRY }}
      if: github.event_name != 'pull_request'
      uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Maven package
      run: |
          chmod +x ./mvnw
          ./mvnw package

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: src/main/docker/Dockerfile.jvm
        push: true
        tags: saschakiebler/thesis-chatbot
