name: Docker

on:
  push:
    branches:
      - master

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    environment: docker

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Maven package with logging
      run: |
        chmod +x ./mvnw
        ./mvnw -Dmaven.test.skip package
      with:
        distribution: 'corretto'
        java-version: '17'

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: src/main/docker/Dockerfile.jvm
        push: true
        tags: saschakiebler/thesis-chatbot:latest
