name: Docker

on:
  push:
    branches:
      - master

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    environment: docker

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: maven
    - name: Build with Maven
      run: mvn -B -Dmaven.test.skip package --file pom.xml

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: src/main/docker/Dockerfile.jvm
        push: true
        tags: saschakiebler/thesis-chatbot:latest
